### ISSUE TITLE
Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "mutex".'

### ISSUE THREAD

**Issue by honsa** [thamtech/yii2-scheduler#1]
Hello

Thank you for this extension.

I installed it an tried to execute the migration scripts, and received the following error:

`Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "mutex".'`

How should I configure this property? 

I tried without success:

`'mutex' => 'mutex`
`'mutex' => 'yii\mutex'`
`'mutex' => 'yii\mutex\Mutex'`
`'mutex' => 'yii\mutex\MysqlMutex'`

**Comment by honsa** [comment]
` 'mutex'=> [
            'class' => 'yii\mutex\MysqlMutex',
         ],`

**Comment by tyler-ham** [comment]
I am re-opening this issue. We should attempt to improve the documentation on how to configure the mutex property.

**Comment by tyler-ham** [comment]
@honsa, I made some adjustments to the mutex example in the documentation in pull request #3. If you have a moment to take a look, I would be interested if you have any feedback on the proposed changes.

**Comment by honsa** [comment]
Looks good, this will help other people.

I also missed some information that, and how you use swiftmailer. For me it is working.
