### ISSUE TITLE
Package mtdowling/cron-expression is abandoned

### ISSUE THREAD

**Issue by honsa** [thamtech/yii2-scheduler#7]
Hello

On update the following message appears:

`Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.`

May you can just replace the required package @tyler-ham

**Comment by tyler-ham** [comment]
Thanks, I will look into this when I have some time.

**Comment by honsa** [comment]
It should not break anything, if you not rely on the bug ;)

> There was a big problem though, and that was that this was a huge backward compatibility break. When a bug has survived long enough and people rely on that behavior, it is no longer a bug - it's a feature. So our bad stepping fix has the potentional for breaking a huge number of systems, even if that behavior is bad. People rely on it.

https://ctankersley.com/2017/10/12/cron-expression-update/
